CREATE TABLE IF NOT EXISTS wp_medi_pending_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pharmacy_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY pharmacy_id (pharmacy_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
