<?php
/**
 * Supplier Email Template
 * Variables replaced dynamically:
 * {{suborder_number}}, {{order_number}}, {{order_date}},
 * {{pharmacy_name}}, {{pharmacy_address}}, {{pharmacy_email}}, {{pharmacy_phone}},
 * {{items_table}}, {{supplier_total}}
 */
?>
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif;">

<h2>New Order Received — Sub‑Order {{suborder_number}}</h2>

<p>Hello,</p>

<p>You have received a new order from <strong>{{pharmacy_name}}</strong>.</p>

<h3>Order Details</h3>
<ul>
    <li><strong>Sub‑Order Number:</strong> {{suborder_number}}</li>
    <li><strong>Master Order Number:</strong> {{order_number}}</li>
    <li><strong>Order Date:</strong> {{order_date}}</li>
</ul>

<h3>Pharmacy Information</h3>
<ul>
    <li><strong>Name:</strong> {{pharmacy_name}}</li>
    <li><strong>Address:</strong> {{pharmacy_address}}</li>
    <li><strong>Email:</strong> {{pharmacy_email}}</li>
    <li><strong>Phone:</strong> {{pharmacy_phone}}</li>
</ul>

<h3>Items in This Sub‑Order</h3>
<table border="1" cellpadding="6" cellspacing="0" width="100%" style="border-collapse: collapse;">
    <thead>
        <tr>
            <th align="left">Product</th>
            <th align="left">Qty</th>
            <th align="left">Unit Price</th>
            <th align="left">Line Total</th>
        </tr>
    </thead>
    <tbody>
        {{items_table}}
    </tbody>
</table>

<h3>Supplier Total</h3>
<p><strong>£{{supplier_total}}</strong></p>

<p>This is an automated order generated by MediCompare.</p>

</body>
</html>
