CREATE TABLE IF NOT EXISTS wp_medi_import_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    admin_id BIGINT UNSIGNED NOT NULL,
    supplier_id BIGINT UNSIGNED DEFAULT NULL,
    filename VARCHAR(255) NOT NULL,
    inserted INT DEFAULT 0,
    updated INT DEFAULT 0,
    errors LONGTEXT DEFAULT NULL,
    ip VARCHAR(100) DEFAULT NULL,
    ua VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY admin_id (admin_id),
    KEY supplier_id (supplier_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
