CREATE TABLE IF NOT EXISTS wp_medi_requirements_board (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    board_json LONGTEXT NOT NULL,
    updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
