name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: FTP Deploy Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload child theme, plugin, vendor and project-req
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PRODUCTION_FTP_HOST }}
          username: ${{ secrets.PRODUCTION_FTP_USERNAME }}
          password: ${{ secrets.PRODUCTION_FTP_PASSWORD }}

          local-dir: public/
          server-dir: /public_html/

          exclude: |
            **/*
            !wp-content/
            !wp-content/themes/
            !wp-content/themes/twentytwentyfive-child/**
            !wp-content/plugins/
            !wp-content/plugins/medicompare/**
            !project-req/**
            !vendor/**
            !composer.json
            !composer.lock