name: Deploy to InfinityFree

on:
  workflow_dispatch:


jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload child theme, plugin, and project-req
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: public/
          server-dir: /htdocs/

          exclude: |
            **/*
            !wp-content/
            !wp-content/themes/
            !wp-content/themes/twentytwentyfive-child/**
            !wp-content/plugins/
            !wp-content/plugins/medicompare/**
            !project-req/**
